Repository DevCycleHQ/go-server-sdk, pull requests merged in 2023-04, with the labels that each got.

#148 DVC-6674 cleanup protobuf wasm workaround
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
  proto/variableForUserParams.pb.go
  proto/variableForUserParams.proto
  proto/variableForUserParams_vtproto.pb.go
Labels: 10 min review

#145 DVC-6664 - validate client options
  client.go
  client_test.go
Labels: 1 min review

#146 Run tests for native Go with test harness
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#149 DVC-6790: Config parsing, bucketing, and segmentation
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/constants.go
  native_bucketing/go.mod
  native_bucketing/go.sum
  native_bucketing/model_bucketed_user_config.go
  native_bucketing/model_config_body.go
  native_bucketing/model_dvc_user.go
  native_bucketing/model_feature.go
  native_bucketing/model_filters.go
  native_bucketing/model_operators.go
  native_bucketing/model_target.go
  native_bucketing/model_target_test.go
  native_bucketing/murmurhash.go
  native_bucketing/segmentation.go
  native_bucketing/segmentation_test.go
  native_bucketing/testdata/audience.json
  native_bucketing/testdata/fixture_test_config.json
  native_bucketing/testing_helpers.go
  native_bucketing/versioncompare.go
Labels: 30 min review

#151 DVC-6908 - Variable for User
  .github/workflows/lint.yml
  bucketing_pool_object.go
  client.go
  eventqueue.go
  localbucketing.go
  logger.go
  model_variable.go
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/go.mod
  native_bucketing/go.sum
  native_bucketing/model_config_body.go
  native_bucketing/model_feature.go
  proto/helpers.go
  request.go
  util/logger.go
Labels: 10 min review

#152 Extract wasm logic from DVCClient into a new wrapper
  bucketing_pool_object.go
  client.go
  client_native.go
  client_wasm.go
  configmanager.go
  configmanager_test.go
  eventqueue.go
  localbucketing.go
  localbucketing_test.go
  native_bucketing/bucketing.go
Labels: 20 min review

#154 Unify model types in new api package
  aliases.go
  api/model_bucketed_user_config.go
  api/model_environment.go
  api/model_error_response.go
  api/model_event.go
  api/model_feature.go
  api/model_feature_variation.go
  api/model_platformdata.go
  api/model_public_project.go
  api/model_user_data.go
  api/model_user_data_and_events_body.go
  api/model_variable.go
  client.go
  client_test.go
  client_wasm_bucketing.go
  localbucketing.go
  model_event_types.go
  model_generic_error.go
  native_bucketing/aliases.go
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/model_bucketed_user_config.go
  native_bucketing/model_config_body.go
  native_bucketing/model_dvc_user.go
  native_bucketing/model_feature.go
  native_bucketing/model_feature_configuration.go
  native_bucketing/model_platform_data.go
  native_bucketing/segmentation.go
  native_bucketing/segmentation_test.go
Labels: 20 min review

#150 DVC-6656 Add benchmark GitHub action
  .github/workflows/bench.yml
Labels: 5 min review

#155 Integrate client with native bucketing
  .github/workflows/run-test-harness.yml
  aliases.go
  api/model_platformdata.go
  api/model_user_data.go
  api/version.go
  client.go
  client_native_bucketing.go
  client_test.go
  client_wasm_bucketing.go
  configmanager.go
  configmanager_test.go
  eventqueue.go
  eventqueue_test.go
  go.mod
  go.sum
  localbucketing.go
  localbucketing_test.go
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/config_manager.go
  native_bucketing/config_manager_test.go
  native_bucketing/datamanager_config.go
  native_bucketing/datamanager_platform.go
  native_bucketing/go.mod
  native_bucketing/go.sum
  native_bucketing/model_config_body.go
  native_bucketing/model_target.go
  testing_helpers.go
  version.go
Labels: 30 min review

#158 Fix lint issues
  .github/workflows/lint.yml
  client.go
  client_test.go
  eventqueue.go
  eventqueue_test.go
  localbucketing.go
  localbucketing_test.go
  native_bucketing/config_manager_test.go
  native_bucketing/model_target_test.go
  native_bucketing/segmentation.go
Labels: 5 min review

#159 setup variable eval and bucketing to use client custom data
  client_native_bucketing.go
Labels: 1 min review

#160 DEV-7024: Fix issues with SetPlatformData in native bucketing
  api/model_platformdata.go
  api/model_user_data.go
  api/version.go
  bucketing_pool.go
  bucketing_pool_factory.go
  bucketing_pool_object.go
  client.go
  client_native_bucketing.go
  client_wasm_bucketing.go
  localbucketing.go
  localbucketing_test.go
  native_bucketing/bucketing_test.go
  native_bucketing/datamanager_platform.go
  version.go
Labels: 10 min review

#161 Prevent errors from being surfaced to the client in variable calls
  client.go
  client_native_bucketing.go
  native_bucketing/bucketing.go
Labels: 1 min review

#162 DVC-7067 - optimized createPopulatedUser()
  api/model_user_data.go
  client_native_bucketing.go
Labels: 1 min review

#163 Optimization in bucketing and segmentation
  native_bucketing/model_config_body.go
  native_bucketing/model_filters.go
  native_bucketing/model_target.go
Labels: 1 min review

#164 Fix contains vs equals in string filters
  native_bucketing/bucketing.go
  native_bucketing/model_feature_configuration.go
  native_bucketing/model_filters.go
  native_bucketing/model_filters_test.go
Labels: 5 min review

#167 Add extra validation and tests to config
  api/model_environment.go
  api/model_public_project.go
  native_bucketing/config_manager.go
  native_bucketing/config_manager_test.go
  native_bucketing/model_config_body.go
  native_bucketing/model_config_body_test.go
Labels: 20 min review

#165 Adding segmentation unit tests
  native_bucketing/segmentation_test.go
Labels: safe-changes, 20 min review

#168 Another unit test to build coverage
  native_bucketing/model_filters_test.go
Labels: 1 min review, safe-changes

#169 bump version
  version.go
Labels: 1 min review

#170 Update examples to show more useful info
  example/cloud/main.go
  example/local/main.go
Labels: 5 min review

#157 DVC-6788 - Native event queue
  api/model_event.go
  api/model_user_data.go
  client_native_bucketing.go
  client_test.go
  configuration.go
  native_bucketing/aliases.go
  native_bucketing/config_manager.go
  native_bucketing/configuration.go
  native_bucketing/constants.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
Labels: 30 min review

#166 adding a new action to generate go native sdk benchmarks
  .github/workflows/bench.yml
Labels: 1 min review

#172 Adding some panic recovery logic
  client.go
  configmanager.go
  eventqueue.go
Labels: 1 min review

#174 Use cancelable context to close channels safely
  native_bucketing/event_queue.go
Labels: 1 min review

#171 DVC-6788 Event Flushing
  api/model_event.go
  api/model_platformdata.go
  api/slices.go
  bucketing_pool.go
  client.go
  client_native_bucketing.go
  client_test.go
  configmanager.go
  configuration.go
  eventqueue.go
  eventqueue_test.go
  localbucketing.go
  native_bucketing/bucketing.go
  native_bucketing/configuration.go
  native_bucketing/constants.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
  native_bucketing/model_filters.go
  request.go
  util/logger.go
  util/slices.go
  wasm_main.go
Labels: 30 min review

#177 Fix concurrent map access
  native_bucketing/event_queue.go
Labels: 1 min review
