Repository DevCycleHQ/go-server-sdk, pull requests merged in 2023-03, with the labels that each got.

#84 fix: log variable defaulted event when calling variable before init
  client.go
  configmanager.go
  eventqueue.go
  localbucketing.go
  localbucketing_test.go
  logger.go
Labels: 5 min review

#83 Test harness update
  .github/workflows/run-test-harness.yml
Labels: 5 min review, safe-changes

#87 chore: optimize function pointer allocation
  localbucketing.go
Labels: 5 min review

#91 Update wasm lib to latest release
  go.mod
  go.sum
  localbucketing.go
Labels: 1 min review

#92 Byte array reads
  localbucketing.go
Labels: 1 min review

#93 Fix UTF-16 handling
  eventqueue.go
  localbucketing.go
  localbucketing_test.go
Labels: 1 min review

#89 chore: add new variableForUser method from WASM
  bucketing-lib.release.wasm
  client.go
  localbucketing.go
Labels: 10 min review

#97 release 2.6.0
  version.go
Labels: 1 min review

#101 refactor local bucketing module to remove ownership over event queue
  client.go
  configmanager.go
  eventqueue.go
  localbucketing.go
  localbucketing_test.go
Labels: 1 min review

#103 refactor wasm code to split reusable stuff from per-thread stuff
  client.go
  localbucketing.go
  localbucketing_test.go
  wasm_main.go
Labels: 5 min review

#106 Memory allocation pool
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
  configuration.go
  localbucketing.go
Labels: 10 min review

#113 integrate protobuf with memory pooling
  localbucketing.go
Labels: 5 min review

#112 Experiment with Protobuf
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
  client.go
  client_test.go
  configmanager.go
  generate.go
  go.mod
  go.sum
  localbucketing.go
  proto/helpers.go
  proto/variableForUserParams.pb.go
  proto/variableForUserParams.proto
  proto/variableForUserParams_vtproto.pb.go
  request.go
  testdata/fixture_large_config.json
  version.go
Labels: 30 min review

#115 Error logging changes
  localbucketing.go
Labels: 5 min review

#116 fix local bucketing unpinning buffer data
  localbucketing.go
  localbucketing_test.go
Labels: 5 min review

#118 fix buffer allocation to use correct class id
  localbucketing.go
Labels: 1 min review

#121 update wasm to avoid leak
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
Labels: 1 min review

#122 fix calling checkdefaults everywhere
  client.go
  localbucketing.go
Labels: 1 min review

#126 batch event queue results back to channel
  client.go
  eventqueue.go
Labels: 10 min review

#102 add support for managed thread pool
  client.go
  client_test.go
  configmanager.go
  configuration.go
  eventqueue.go
  go.mod
  go.sum
  localbucketing.go
  localbucketing_test.go
  thread_pool.go
  wasm_main.go
Labels: 30 min review

#127 DVC-6635 Update to latest proto file
  proto/variableForUserParams.pb.go
  proto/variableForUserParams.proto
  proto/variableForUserParams_vtproto.pb.go
Labels: 20 min review

#129 POC of using object pool for variable evaluations
  bucketing_pool.go
  bucketing_pool_factory.go
  bucketing_pool_object.go
  client.go
  configmanager.go
  eventqueue.go
  go.mod
  go.sum
  thread_pool.go
Labels: 20 min review

#134 Update version.go
  version.go
Labels: 1 min review

#132 stop using channel to handle flush results and unify result handling
  bucketing_pool_object.go
  eventqueue.go
  localbucketing.go
Labels: 5 min review

#135 DVC-6731 set json config data with utf8 byte arrays
  bench/testdata/fixture_small_config_special_characters.json
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
  client_test.go
  localbucketing.go
  localbucketing_test.go
  testing_helpers.go
Labels: 20 min review

#139 Update WASM files built with GC optimizations
  bucketing-lib.debug.wasm
  bucketing-lib.release.wasm
Labels: 1 min review

#140 update version.go
  version.go
Labels: 1 min review

#141 Removing old WASM function references
  localbucketing.go
Labels: 1 min review

#142 DVC-6813: Retry config fetching on network error
  bucketing_pool.go
  client.go
  configmanager.go
  configmanager_test.go
  testing_helpers.go
Labels: 20 min review

#143 Update version to 2.9.4
  version.go
Labels: 1 min review

#144 Fix WASM error when Track called before config loads
  client.go
  client_test.go
Labels: 1 min review
