Repository DevCycleHQ/go-server-sdk, pull requests merged in 2023-05, with the labels that each got.

#179 Re-merge benchmark util.
  bench-dd/README.md
  bench-dd/go.mod
  bench-dd/go.sum
  bench-dd/main.go
  bench-dd/testdata.go
  bench-dd/testdata/fixture_large_config.json
  bench-dd/testdata/fixture_small_config.json
  bench-dd/testdata/fixture_small_config_special_characters.json
  bench/main.go
  testdata/fixture_large_config.json
  testdata/fixture_small_config.json
  testdata/fixture_small_config_special_characters.json
  testing_helpers.go
Labels: 30 min review

#178 Don't build native version with CGO
  .github/workflows/bench.yml
  .github/workflows/test.yml
  api/model_event.go
  bucketing_pool.go
  bucketing_pool_factory.go
  bucketing_pool_object.go
  eventqueue.go
  eventqueue_test.go
  generate.go
  localbucketing.go
  localbucketing_test.go
  native_bucketing/event_queue.go
  testing_helpers.go
  wasm_main.go
Labels: 1 min review

#180 Updating readme files
  README.md
  bench-dd/README.md
Labels: 1 min review, safe-changes

#181 DVC 7187: Restore logs API and reduce noise
  aliases.go
  eventqueue_test.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
Labels: 1 min review

#173 DVC-7086 - log bucketing system on init
  client.go
Labels: 1 min review

#182 bump version to 2.9.6
  version.go
Labels: 1 min review

#183 DVC 7015: Remove DVC prefixes and aliases
  aliases.go
  api/model_bucketed_user_config.go
  api/model_event.go
  api/model_user_data.go
  api/model_user_data_and_events_body.go
  api/slices.go
  bench-dd/testdata.go
  bucketing_pool.go
  bucketing_pool_factory.go
  bucketing_pool_object.go
  client.go
  client_native_bucketing.go
  client_test.go
  client_wasm_bucketing.go
  configmanager.go
  configuration.go
  eventqueue.go
  eventqueue_test.go
  example/cloud/main.go
  example/local/main.go
  localbucketing.go
  localbucketing_test.go
  native_bucketing/aliases.go
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
  native_bucketing/model_config_body.go
  native_bucketing/model_config_body_test.go
  native_bucketing/model_feature_configuration.go
  native_bucketing/segmentation.go
  native_bucketing/segmentation_test.go
  testing_helpers.go
  util/slices.go
  wasm_main.go
Labels: 20 min review

#184 DVC-7189 collect event bench metrics
  .github/workflows/bench.yml
  api/model_event.go
  bench-dd/go.mod
  bench-dd/main.go
  client.go
  client_test.go
  configuration.go
  eventqueue.go
  native_bucketing/event_queue.go
Labels: 5 min review

#186 Updated readme with options settings
  README.md
Labels: 1 min review, safe-changes

#187 fixed some spelling mistakes
  README.md
Labels: 1 min review, safe-changes

#189 DVC-7156 add VariableValue method
  client.go
  client_test.go
  example/cloud/main.go
  example/local/main.go
Labels: 10 min review

#188 Refactor the event queue
  .github/workflows/bench.yml
  aliases.go
  client.go
  client_native_bucketing.go
  client_wasm_bucketing.go
  event_manager.go
  event_manager_test.go
  eventqueue.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
  wasm_bucketing.go
  wasm_bucketing_test.go
Labels: 30 min review

#191 Move lint and tests to Makefile
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  Makefile
  README.md
Labels: 1 min review

#192 remove use of util.Errorf for returning errors
  bucketing_pool.go
  client.go
  client_native_bucketing.go
  configmanager.go
  event_manager.go
  native_bucketing/event_queue.go
  request.go
  util/logger_debug.go
  util/logger_disabled.go
  wasm_bucketing.go
Labels: 5 min review

#190 More performance optimizations
  README.md
  api/model_event.go
  bench-dd/main.go
  bench-dd/testdata.go
  bucketing_pool.go
  client.go
  client_native_bucketing.go
  configmanager.go
  event_manager.go
  native_bucketing/bucketing.go
  native_bucketing/bucketing_test.go
  native_bucketing/constants.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
  native_bucketing/model_config_body.go
  native_bucketing/model_config_body_test.go
  native_bucketing/model_feature.go
  request.go
  util/logger_debug.go
  util/logger_disabled.go
  util/logging.go
  wasm_bucketing.go
Labels: 20 min review

#193 DVC 7411: Fix race conditions and turn on race detector
  .github/workflows/test.yml
  README.md
  event_manager_test.go
  go.mod
  go.sum
  native_bucketing/bucketing.go
  native_bucketing/event_queue.go
  native_bucketing/event_queue_test.go
  native_bucketing/murmurhash.go
  native_bucketing/murmurhash_test.go
  wasm_bucketing_test.go
Labels: 1 min review

#194 switch to using native bucketing by default without a build tag
  .github/workflows/bench.yml
  .github/workflows/lint.yml
  .github/workflows/run-test-harness.yml
  .github/workflows/test.yml
  Makefile
  README.md
  aliases.go
  bucketing/bucketing.go
  bucketing/bucketing_test.go
  bucketing/config_manager.go
  bucketing/config_manager_test.go
  bucketing/configuration.go
  bucketing/constants.go
  bucketing/datamanager_platform.go
  bucketing/event_queue.go
  bucketing/event_queue_test.go
  bucketing/model_config_body.go
  bucketing/model_config_body_test.go
  bucketing/model_feature.go
  bucketing/model_feature_configuration.go
  bucketing/model_filters.go
  bucketing/model_filters_test.go
  bucketing/model_operators.go
  bucketing/model_target.go
  bucketing/model_target_test.go
  bucketing/murmurhash.go
  bucketing/murmurhash_test.go
  bucketing/segmentation.go
  bucketing/segmentation_test.go
  bucketing/testdata/audience.json
  bucketing/testdata/fixture_test_config.json
  bucketing/versioncompare.go
  bucketing_pool.go
  bucketing_pool_factory.go
  bucketing_pool_object.go
  client_native_bucketing.go
  client_wasm_bucketing.go
  event_manager.go
  generate.go
  wasm_bucketing.go
  wasm_bucketing_test.go
  wasm_main.go
Labels: 5 min review

#185 Allow bypassing the variable default type checks; PlatformData passthroughs
  bucketing/bucketing.go
  bucketing/configuration.go
  bucketing/event_queue.go
  bucketing/event_queue_test.go
  client.go
  client_native_bucketing.go
  client_test.go
  configmanager.go
  configuration.go
Labels: 5 min review

#195 Test for zero allocation flow
  .github/workflows/test.yml
Labels: 1 min review, safe-changes

#197 DVC-7444: Release workflow for updating version.go
  .github/workflows/release.yml
Labels: 5 min review
