Repository DevCycleHQ/go-server-sdk, pull requests merged in 2023-02, with the labels that each got.

#67 change environmentKey to be sdkKey
  README.md
  bucketing-lib.release.wasm
  client.go
  configmanager.go
  example/cloud/main.go
  example/local/main.go
Labels: 1 min review

#68 bump version to 2.1.0
  version.go
Labels: 1 min review

#70 add setClientCustomData method to SDK
  .github/workflows/update-wasm.yaml
  bucketing-lib.release.wasm
  client.go
  localbucketing.go
  localbucketing_test.go
Labels: 5 min review

#71 version 2.2.1
  bucketing-lib.release.wasm
  version.go
Labels: 1 min review

#75 fix outbound event payloads and handle 4xx errors
  eventqueue.go
  model_event.go
Labels: 1 min review

#69 Add error handling to wasm calls to prevent panic crashes.
  localbucketing.go
Labels: 5 min review

#78 add back some omitempty
  model_event.go
Labels: 1 min review

#77 DVC-6277 - Create custom logging wrapper
  client.go
  configmanager.go
  configuration.go
  eventqueue.go
  git_push.sh
  localbucketing.go
  logger.go
Labels: 10 min review

#79 Update version to 2.4.0
  version.go
Labels: 1 min review

#81 Ensure that sdkKeys are pinned in ASC memory
  client.go
  configmanager.go
  localbucketing.go
  localbucketing_test.go
Labels: 10 min review
