Repository DevCycleHQ/go-server-sdk, pull requests merged in 2023-06, with the labels that each got.

#198 fix casting of audienceMatch filters
  bucketing/segmentation.go
  bucketing/segmentation_test.go
Labels: 1 min review

#199 Fix issues with retagging releases
  .github/workflows/release.yml
Labels: 1 min review

#200 Bump version to v2.10.3
  version.go
Labels: 1 min review

#201 DVC-7598 version filter test
  bucketing/model_filters.go
  bucketing/model_filters_test.go
  bucketing/versioncompare.go
Labels: 20 min review

#202 DVC-7596-checkStringsFilter
  bucketing/model_filters_test.go
Labels: 1 min review, safe-changes

#203 DVC-7595 - basic user filter tests
  bucketing/segmentation_test.go
Labels: safe-changes, 20 min review

#204 Test for nested audience filters
  bucketing/segmentation_test.go
Labels: 5 min review, safe-changes

#205 DVC-7599 check custom data filter
  bucketing/model_filters_test.go
  bucketing/segmentation_test.go
Labels: safe-changes, 20 min review

#207 DVC-7593 - unit test evaluating matching multiple audiences
  bucketing/segmentation_test.go
Labels: 10 min review, safe-changes

#209 more unit tests around custom data
  bucketing/segmentation_test.go
Labels: 10 min review, safe-changes

#208 DVC-7611: Test for order of matching targets
  bucketing/bucketing_test.go
Labels: 1 min review, safe-changes

#210 DVC 7612: Rollouts
  bucketing/bucketing.go
  bucketing/bucketing_test.go
Labels: 1 min review

#211 DVC-7600 - filter audience unit tests
  bucketing/segmentation_test.go
Labels: 10 min review, safe-changes

#212 DVC-7614 -
  bucketing/bucketing_test.go
Labels: 1 min review, safe-changes

#213 DVC-7613: add tests for missing distributions, variations, and variables
  bucketing/bucketing.go
  bucketing/bucketing_test.go
  bucketing/model_target.go
  bucketing/testdata/fixture_test_broken_config.json
Labels: 5 min review

#214 DVC-7677 use 4 core actions runner for test harness
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#215 DVC-6956: Refactor config structure
  .swagger-codegen-ignore
  bucketing/bucketing.go
  bucketing/bucketing_test.go
  bucketing/datamanager_platform.go
  bucketing/model_filters.go
  bucketing/model_filters_test.go
  bucketing/model_operators.go
  bucketing/model_target_test.go
  bucketing/segmentation.go
  bucketing/segmentation_test.go
  configuration.go
  response.go
Labels: 20 min review

#216 Bump version and fix http client timeouts
  bucketing/event_queue.go
  configmanager.go
  configuration.go
  version.go
Labels: 1 min review
